
    [fr000gs@archlinux ~]$ clang -Wall -I /usr/include -I /usr/include/python3.10 -v pyssword032.c -o pyssword032
    clang version 14.0.6
    Target: x86_64-pc-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/12.2.0
    Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0
    Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0
    Candidate multilib: .;@m64
    Candidate multilib: 32;@m32
    Selected multilib: .;@m64
     "/usr/bin/clang-14" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name pyssword032.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/fr000gs -resource-dir /usr/lib/clang/14.0.6 -I /usr/include -I /usr/include/python3.10 -internal-isystem /usr/lib/clang/14.0.6/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -fdebug-compilation-dir=/home/fr000gs -ferror-limit 19 -stack-protector 2 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/pyssword032-799af8.o -x c pyssword032.c
    clang -cc1 version 14.0.6 based upon LLVM 14.0.6 default target x86_64-pc-linux-gnu
    ignoring nonexistent directory "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/include"
    ignoring nonexistent directory "/include"
    ignoring duplicate directory "/usr/include"
      as it is a non-system directory that duplicates a system directory
    #include "..." search starts here:
    #include <...> search starts here:
     /usr/include/python3.10
     /usr/lib/clang/14.0.6/include
     /usr/local/include
     /usr/include
    End of search list.
     "/usr/bin/ld" -pie --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o pyssword032 /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64/Scrt1.o /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64/crti.o /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/crtbeginS.o -L/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0 -L/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/lib -L/usr/lib /tmp/pyssword032-799af8.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/crtendS.o /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64/crtn.o
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `PyInit_pyssword03':
    pyssword032.c:(.text+0xc): undefined reference to `PyModuleDef_Init'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `main':
    pyssword032.c:(.text+0x1c3): undefined reference to `PyMem_RawFree'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_main':
    pyssword032.c:(.text+0x22c): undefined reference to `Py_SetProgramName'
    /usr/bin/ld: pyssword032.c:(.text+0x231): undefined reference to `Py_Initialize'
    /usr/bin/ld: pyssword032.c:(.text+0x252): undefined reference to `PySys_SetArgv'
    /usr/bin/ld: pyssword032.c:(.text+0x278): undefined reference to `PyModule_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x29a): undefined reference to `PyUnicode_FromString'
    /usr/bin/ld: pyssword032.c:(.text+0x2ba): undefined reference to `PyModule_NewObject'
    /usr/bin/ld: pyssword032.c:(.text+0x2df): undefined reference to `PyModule_ExecDef'
    /usr/bin/ld: pyssword032.c:(.text+0x2ee): undefined reference to `PyErr_Occurred'
    /usr/bin/ld: pyssword032.c:(.text+0x2fd): undefined reference to `PyErr_Print'
    /usr/bin/ld: pyssword032.c:(.text+0x317): undefined reference to `Py_FinalizeEx'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__pyx_pymod_create':
    pyssword032.c:(.text+0x6d9): undefined reference to `PyObject_GetAttrString'
    /usr/bin/ld: pyssword032.c:(.text+0x70a): undefined reference to `PyModule_NewObject'
    /usr/bin/ld: pyssword032.c:(.text+0x744): undefined reference to `PyModule_GetDict'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__pyx_pymod_exec_pyssword03':
    pyssword032.c:(.text+0x91b): undefined reference to `PyExc_RuntimeError'
    /usr/bin/ld: pyssword032.c:(.text+0x92a): undefined reference to `PyErr_SetString'
    /usr/bin/ld: pyssword032.c:(.text+0x96b): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x9c2): undefined reference to `PyBytes_FromStringAndSize'
    /usr/bin/ld: pyssword032.c:(.text+0xa19): undefined reference to `PyUnicode_FromStringAndSize'
    /usr/bin/ld: pyssword032.c:(.text+0xaaf): undefined reference to `PyModule_GetDict'
    /usr/bin/ld: pyssword032.c:(.text+0xb0e): undefined reference to `PyImport_AddModule'
    /usr/bin/ld: pyssword032.c:(.text+0xb6d): undefined reference to `PyImport_AddModule'
    /usr/bin/ld: pyssword032.c:(.text+0xbda): undefined reference to `PyObject_SetAttrString'
    /usr/bin/ld: pyssword032.c:(.text+0xc54): undefined reference to `PyObject_SetAttr'
    /usr/bin/ld: pyssword032.c:(.text+0xc85): undefined reference to `PyImport_GetModuleDict'
    /usr/bin/ld: pyssword032.c:(.text+0xcd6): undefined reference to `PyDict_GetItemString'
    /usr/bin/ld: pyssword032.c:(.text+0xcf7): undefined reference to `PyDict_SetItemString'
    /usr/bin/ld: pyssword032.c:(.text+0xe1a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xe5c): undefined reference to `PyList_New'
    /usr/bin/ld: pyssword032.c:(.text+0xfce): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x1021): undefined reference to `PyList_New'
    /usr/bin/ld: pyssword032.c:(.text+0x1193): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x11e6): undefined reference to `PyList_New'
    /usr/bin/ld: pyssword032.c:(.text+0x1358): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x13ab): undefined reference to `PyList_New'
    /usr/bin/ld: pyssword032.c:(.text+0x151d): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x1570): undefined reference to `PyList_New'
    /usr/bin/ld: pyssword032.c:(.text+0x16e8): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x173b): undefined reference to `PyList_New'
    /usr/bin/ld: pyssword032.c:(.text+0x18b3): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x1916): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x1b09): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x1e21): undefined reference to `PyObject_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x20c4): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x2184): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x2244): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x2476): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x251d): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x2575): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x25b3): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x25f1): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x262f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x26f2): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x2889): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x28e1): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x291f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x2bc8): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x2c6f): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x2cc7): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x2d8a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x2f21): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x2f79): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x2fb7): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x3260): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x3307): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x335f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x3422): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x35b9): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x3611): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x364f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x38f8): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x399f): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x39f7): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x3aba): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x3c51): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x3ca9): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x3ce7): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x3f90): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x4037): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x408f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x4152): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x42e9): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x4341): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x437f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x4628): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x46cf): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x4727): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x47ea): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x4981): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x49d9): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x4a17): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x4c30): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x4e62): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x4f09): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x5056): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x519a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x526e): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x55cb): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x5623): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x5661): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x587a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x5aac): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x5b53): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x5ca0): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x5de4): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x5eb8): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x6215): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x626d): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x62ab): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x64c4): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x66f6): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x679d): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x68ea): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x6a2e): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x6b02): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x6c99): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x6cf1): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x6d2f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x6f48): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x717a): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x7221): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x736e): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x74b2): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x7586): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x771d): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x7775): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x77b3): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x7b3b): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x7cd2): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x7d2a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x7d68): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x7da6): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x7fb4): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x800c): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x804a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x81df): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x82a5): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x843c): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x85eb): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x880a): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x8862): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x88a0): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x88de): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x891c): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x8ca4): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x8e3b): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x8e93): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x8ed1): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x8f0f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x911d): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x9175): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x91b3): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x9348): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x940e): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x95a5): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x9754): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x9973): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x99cb): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x9a09): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x9a47): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x9a85): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x9e0d): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x9fa4): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x9ffc): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xa03a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xa078): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xa286): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xa2de): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xa31c): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xa4b1): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xa577): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xa70e): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xa8bd): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xaadc): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xab34): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xab72): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xabb0): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xabee): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xb053): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0xb452): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xb5e9): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xb641): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xb67f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xb6bd): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xb6fb): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xba06): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0xbaad): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xbb05): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xbc9a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xbce9): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xbdac): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xbf43): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xbf9b): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xbfd9): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc017): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc055): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc360): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0xc407): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xc45f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc592): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc5e1): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc6a4): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc83b): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xc893): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc8d1): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc90f): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xc94d): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xcc58): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0xccff): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xcd57): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xce8a): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xced9): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xcf9c): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xd133): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xd18b): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xd1c9): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xd207): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xd245): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xd623): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xd67b): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xd755): undefined reference to `PyErr_Occurred'
    /usr/bin/ld: pyssword032.c:(.text+0xd766): undefined reference to `PyExc_ImportError'
    /usr/bin/ld: pyssword032.c:(.text+0xd775): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_check_single_interpreter':
    pyssword032.c:(.text+0xd7b9): undefined reference to `PyThreadState_Get'
    /usr/bin/ld: pyssword032.c:(.text+0xd7c2): undefined reference to `PyInterpreterState_GetID'
    /usr/bin/ld: pyssword032.c:(.text+0xd833): undefined reference to `PyExc_ImportError'
    /usr/bin/ld: pyssword032.c:(.text+0xd842): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `_Py_DECREF':
    pyssword032.c:(.text+0xd8be): undefined reference to `_Py_Dealloc'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_copy_spec_to_module':
    pyssword032.c:(.text+0xd8f5): undefined reference to `PyObject_GetAttrString'
    /usr/bin/ld: pyssword032.c:(.text+0xd92e): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0xd949): undefined reference to `PyDict_SetItemString'
    /usr/bin/ld: pyssword032.c:(.text+0xd961): undefined reference to `PyExc_AttributeError'
    /usr/bin/ld: pyssword032.c:(.text+0xd969): undefined reference to `PyErr_ExceptionMatches'
    /usr/bin/ld: pyssword032.c:(.text+0xd977): undefined reference to `PyErr_Clear'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_check_binary_version':
    pyssword032.c:(.text+0xd9f3): undefined reference to `Py_GetVersion'
    /usr/bin/ld: pyssword032.c:(.text+0xda1f): undefined reference to `PyOS_snprintf'
    /usr/bin/ld: pyssword032.c:(.text+0xdc12): undefined reference to `PyOS_snprintf'
    /usr/bin/ld: pyssword032.c:(.text+0xdc27): undefined reference to `PyErr_WarnEx'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_InitGlobals':
    pyssword032.c:(.text+0xdd29): undefined reference to `PyLong_FromLong'
    /usr/bin/ld: pyssword032.c:(.text+0xdd83): undefined reference to `PyLong_FromLong'
    /usr/bin/ld: pyssword032.c:(.text+0xdddd): undefined reference to `PyLong_FromLong'
    /usr/bin/ld: pyssword032.c:(.text+0xde37): undefined reference to `PyLong_FromLong'
    /usr/bin/ld: pyssword032.c:(.text+0xde91): undefined reference to `PyLong_FromLong'
    /usr/bin/ld: /tmp/pyssword032-799af8.o:pyssword032.c:(.text+0xdeeb): more undefined references to `PyLong_FromLong' follow
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_InitCachedConstants':
    pyssword032.c:(.text+0xe15b): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0xe163): undefined reference to `PySlice_New'
    /usr/bin/ld: pyssword032.c:(.text+0xe1c6): undefined reference to `PyTuple_Pack'
    /usr/bin/ld: pyssword032.c:(.text+0xe229): undefined reference to `PyTuple_Pack'
    /usr/bin/ld: pyssword032.c:(.text+0xe285): undefined reference to `_Py_TrueStruct'
    /usr/bin/ld: pyssword032.c:(.text+0xe28f): undefined reference to `PyTuple_Pack'
    /usr/bin/ld: pyssword032.c:(.text+0xe300): undefined reference to `PyTuple_Pack'
    /usr/bin/ld: pyssword032.c:(.text+0xe3d2): undefined reference to `PyCode_New'
    /usr/bin/ld: pyssword032.c:(.text+0xe4a3): undefined reference to `PyCode_New'
    /usr/bin/ld: pyssword032.c:(.text+0xe574): undefined reference to `PyCode_New'
    /usr/bin/ld: pyssword032.c:(.text+0xe5de): undefined reference to `PyTuple_Pack'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_Import':
    pyssword032.c:(.text+0xe720): undefined reference to `PyList_New'
    /usr/bin/ld: pyssword032.c:(.text+0xe748): undefined reference to `PyModule_GetDict'
    /usr/bin/ld: pyssword032.c:(.text+0xe761): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0xe7aa): undefined reference to `PyImport_ImportModuleLevelObject'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_ImportFrom':
    pyssword032.c:(.text+0xe863): undefined reference to `PyExc_AttributeError'
    /usr/bin/ld: pyssword032.c:(.text+0xe86b): undefined reference to `PyErr_ExceptionMatches'
    /usr/bin/ld: pyssword032.c:(.text+0xe87b): undefined reference to `PyExc_ImportError'
    /usr/bin/ld: pyssword032.c:(.text+0xe890): undefined reference to `PyErr_Format'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_GetBuiltinName':
    pyssword032.c:(.text+0xe8e2): undefined reference to `PyExc_NameError'
    /usr/bin/ld: pyssword032.c:(.text+0xe8f7): undefined reference to `PyErr_Format'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx__GetModuleGlobalName':
    pyssword032.c:(.text+0xe938): undefined reference to `_PyDict_GetItem_KnownHash'
    /usr/bin/ld: pyssword032.c:(.text+0xe991): undefined reference to `PyErr_Occurred'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyObject_GetAttrStr':
    pyssword032.c:(.text+0xea47): undefined reference to `PyObject_GetAttr'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyObject_CallNoArg':
    pyssword032.c:(.text+0xea73): undefined reference to `PyCFunction_Type'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyObject_Call':
    pyssword032.c:(.text+0xeb83): undefined reference to `PyObject_Call'
    /usr/bin/ld: pyssword032.c:(.text+0xeb98): undefined reference to `Py_EnterRecursiveCall'
    /usr/bin/ld: pyssword032.c:(.text+0xebdb): undefined reference to `Py_LeaveRecursiveCall'
    /usr/bin/ld: pyssword032.c:(.text+0xebff): undefined reference to `PyErr_Occurred'
    /usr/bin/ld: pyssword032.c:(.text+0xec24): undefined reference to `PyExc_SystemError'
    /usr/bin/ld: pyssword032.c:(.text+0xec33): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_New':
    pyssword032.c:(.text+0xec7b): undefined reference to `_PyObject_GC_New'
    /usr/bin/ld: pyssword032.c:(.text+0xecd1): undefined reference to `PyObject_GC_Track'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyObject_CallOneArg':
    pyssword032.c:(.text+0xecf7): undefined reference to `PyCFunction_Type'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_AddTraceback':
    pyssword032.c:(.text+0xedb4): undefined reference to `_PyThreadState_UncheckedGet'
    /usr/bin/ld: pyssword032.c:(.text+0xeeb2): undefined reference to `PyFrame_New'
    /usr/bin/ld: pyssword032.c:(.text+0xeed9): undefined reference to `PyTraceBack_Here'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_FetchCommonType':
    pyssword032.c:(.text+0xef2c): undefined reference to `PyImport_AddModule'
    /usr/bin/ld: pyssword032.c:(.text+0xef62): undefined reference to `PyObject_GetAttrString'
    /usr/bin/ld: pyssword032.c:(.text+0xef8a): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0xefa3): undefined reference to `PyErr_Format'
    /usr/bin/ld: pyssword032.c:(.text+0xefc5): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0xefde): undefined reference to `PyErr_Format'
    /usr/bin/ld: pyssword032.c:(.text+0xefef): undefined reference to `PyExc_AttributeError'
    /usr/bin/ld: pyssword032.c:(.text+0xeff7): undefined reference to `PyErr_ExceptionMatches'
    /usr/bin/ld: pyssword032.c:(.text+0xf00a): undefined reference to `PyErr_Clear'
    /usr/bin/ld: pyssword032.c:(.text+0xf013): undefined reference to `PyType_Ready'
    /usr/bin/ld: pyssword032.c:(.text+0xf036): undefined reference to `PyObject_SetAttrString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_dealloc':
    pyssword032.c:(.text+0xf0e1): undefined reference to `PyObject_GC_UnTrack'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_repr':
    pyssword032.c:(.text+0xf122): undefined reference to `PyUnicode_FromFormat'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_CallAsMethod':
    pyssword032.c:(.text+0xf1d1): undefined reference to `PyTuple_GetSlice'
    /usr/bin/ld: pyssword032.c:(.text+0xf20e): undefined reference to `PyTuple_GetItem'
    /usr/bin/ld: pyssword032.c:(.text+0xf241): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0xf25a): undefined reference to `PyErr_Format'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_clear':
    pyssword032.c:(.text+0xf9a1): undefined reference to `PyObject_Free'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_descr_get':
    pyssword032.c:(.text+0xf9e8): undefined reference to `PyMethod_New'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx__CyFunction_dealloc':
    pyssword032.c:(.text+0xfa30): undefined reference to `PyObject_ClearWeakRefs'
    /usr/bin/ld: pyssword032.c:(.text+0xfa42): undefined reference to `PyObject_GC_Del'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_CallMethod':
    pyssword032.c:(.text+0xfac9): undefined reference to `PyDict_Size'
    /usr/bin/ld: pyssword032.c:(.text+0xfb3b): undefined reference to `PyDict_Size'
    /usr/bin/ld: pyssword032.c:(.text+0xfbe3): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0xfc03): undefined reference to `PyErr_Format'
    /usr/bin/ld: pyssword032.c:(.text+0xfc2e): undefined reference to `PyDict_Size'
    /usr/bin/ld: pyssword032.c:(.text+0xfd29): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0xfd49): undefined reference to `PyErr_Format'
    /usr/bin/ld: pyssword032.c:(.text+0xfd62): undefined reference to `PyExc_SystemError'
    /usr/bin/ld: pyssword032.c:(.text+0xfd71): undefined reference to `PyErr_SetString'
    /usr/bin/ld: pyssword032.c:(.text+0xfd85): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0xfda1): undefined reference to `PyErr_Format'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_doc':
    pyssword032.c:(.text+0xfe81): undefined reference to `PyUnicode_FromString'
    /usr/bin/ld: pyssword032.c:(.text+0xfec6): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0xfed2): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_set_doc':
    pyssword032.c:(.text+0xff3e): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_name':
    pyssword032.c:(.text+0xffad): undefined reference to `PyUnicode_InternFromString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_set_name':
    pyssword032.c:(.text+0x1007c): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0x1008b): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_set_qualname':
    pyssword032.c:(.text+0x1016c): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0x1017b): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_self':
    pyssword032.c:(.text+0x101fa): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_dict':
    pyssword032.c:(.text+0x10252): undefined reference to `PyDict_New'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_set_dict':
    pyssword032.c:(.text+0x102f4): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0x10303): undefined reference to `PyErr_SetString'
    /usr/bin/ld: pyssword032.c:(.text+0x10345): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0x10354): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_closure':
    pyssword032.c:(.text+0x103e3): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x103ef): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_code':
    pyssword032.c:(.text+0x10433): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_defaults':
    pyssword032.c:(.text+0x104e6): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_set_defaults':
    pyssword032.c:(.text+0x10532): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o:pyssword032.c:(.text+0x10542): more undefined references to `_Py_NoneStruct' follow
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_set_defaults':
    pyssword032.c:(.text+0x1056e): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0x1057d): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_kwdefaults':
    pyssword032.c:(.text+0x10666): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_set_kwdefaults':
    pyssword032.c:(.text+0x106b2): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x106c2): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x106ee): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0x106fd): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_get_annotations':
    pyssword032.c:(.text+0x1079f): undefined reference to `PyDict_New'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CyFunction_set_annotations':
    pyssword032.c:(.text+0x10822): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x1085b): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0x1086a): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_InitStrings':
    pyssword032.c:(.text+0x10a6c): undefined reference to `PyUnicode_InternFromString'
    /usr/bin/ld: pyssword032.c:(.text+0x10ab2): undefined reference to `PyUnicode_Decode'
    /usr/bin/ld: pyssword032.c:(.text+0x10add): undefined reference to `PyUnicode_FromStringAndSize'
    /usr/bin/ld: pyssword032.c:(.text+0x10b0d): undefined reference to `PyBytes_FromStringAndSize'
    /usr/bin/ld: pyssword032.c:(.text+0x10b46): undefined reference to `PyObject_Hash'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `_PyObject_TypeCheck':
    pyssword032.c:(.text+0x10bca): undefined reference to `PyType_IsSubtype'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyObject_CallMethO':
    pyssword032.c:(.text+0x10dae): undefined reference to `Py_EnterRecursiveCall'
    /usr/bin/ld: pyssword032.c:(.text+0x10ded): undefined reference to `Py_LeaveRecursiveCall'
    /usr/bin/ld: pyssword032.c:(.text+0x10e11): undefined reference to `PyErr_Occurred'
    /usr/bin/ld: pyssword032.c:(.text+0x10e36): undefined reference to `PyExc_SystemError'
    /usr/bin/ld: pyssword032.c:(.text+0x10e45): undefined reference to `PyErr_SetString'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_InBases':
    pyssword032.c:(.text+0x10ed8): undefined reference to `PyBaseObject_Type'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__pyx_pf_10pyssword03_pswd':
    pyssword032.c:(.text+0x1129e): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x11549): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x117ed): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x11931): undefined reference to `PyNumber_Add'
    /usr/bin/ld: pyssword032.c:(.text+0x11aaf): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x11c54): undefined reference to `PyNumber_Add'
    /usr/bin/ld: pyssword032.c:(.text+0x11c9f): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x11db4): undefined reference to `PyBytes_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x11e22): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x11fe7): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x12190): undefined reference to `PyNumber_Add'
    /usr/bin/ld: pyssword032.c:(.text+0x121f9): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x124ff): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x125a8): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x12b7d): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x12c26): undefined reference to `PyTuple_New'
    /usr/bin/ld: pyssword032.c:(.text+0x12e35): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x12e40): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyObject_Call2Args':
    pyssword032.c:(.text+0x12ef2): undefined reference to `PyTuple_New'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyObject_GetIndex':
    pyssword032.c:(.text+0x130fc): undefined reference to `PyExc_TypeError'
    /usr/bin/ld: pyssword032.c:(.text+0x13119): undefined reference to `PyErr_Format'
    /usr/bin/ld: pyssword032.c:(.text+0x13148): undefined reference to `PyErr_Occurred'
    /usr/bin/ld: pyssword032.c:(.text+0x1319c): undefined reference to `PyExc_OverflowError'
    /usr/bin/ld: pyssword032.c:(.text+0x131a4): undefined reference to `PyErr_GivenExceptionMatches'
    /usr/bin/ld: pyssword032.c:(.text+0x131b2): undefined reference to `PyErr_Clear'
    /usr/bin/ld: pyssword032.c:(.text+0x131b9): undefined reference to `PyExc_IndexError'
    /usr/bin/ld: pyssword032.c:(.text+0x131d6): undefined reference to `PyErr_Format'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyIndex_AsSsize_t':
    pyssword032.c:(.text+0x13203): undefined reference to `PyLong_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x1334d): undefined reference to `PyLong_AsSsize_t'
    /usr/bin/ld: pyssword032.c:(.text+0x1335f): undefined reference to `PyNumber_Index'
    /usr/bin/ld: pyssword032.c:(.text+0x13384): undefined reference to `PyLong_AsSsize_t'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_GetItemInt_Fast':
    pyssword032.c:(.text+0x133de): undefined reference to `PyList_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x13582): undefined reference to `PyTuple_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x137fb): undefined reference to `PyExc_OverflowError'
    /usr/bin/ld: pyssword032.c:(.text+0x13803): undefined reference to `PyErr_ExceptionMatches'
    /usr/bin/ld: pyssword032.c:(.text+0x1381e): undefined reference to `PyErr_Clear'
    /usr/bin/ld: pyssword032.c:(.text+0x1385c): undefined reference to `PyLong_FromSsize_t'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_GetItemInt_Generic':
    pyssword032.c:(.text+0x138d1): undefined reference to `PyObject_GetItem'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__pyx_pf_10pyssword03_2ctoc':
    pyssword032.c:(.text+0x139ab): undefined reference to `_PyThreadState_UncheckedGet'
    /usr/bin/ld: pyssword032.c:(.text+0x13b31): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x1422e): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x14396): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x143a1): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyErr_GivenExceptionMatches':
    pyssword032.c:(.text+0x1465f): undefined reference to `PyErr_GivenExceptionMatches'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx__GetException':
    pyssword032.c:(.text+0x1477a): undefined reference to `PyErr_NormalizeException'
    /usr/bin/ld: pyssword032.c:(.text+0x147b8): undefined reference to `PyException_SetTraceback'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyErr_GetTopmostException':
    pyssword032.c:(.text+0x149ce): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__pyx_pf_10pyssword03_4show_toggle':
    pyssword032.c:(.text+0x14ebe): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x151a6): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x151fe): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x15411): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x15469): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x15685): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x1596d): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x159c5): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x15bd8): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x15c30): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x15e4c): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x16134): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x1618c): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x1639f): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x163f7): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x16613): undefined reference to `PyMethod_Type'
    /usr/bin/ld: pyssword032.c:(.text+0x168fb): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x16953): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x16b66): undefined reference to `PyDict_New'
    /usr/bin/ld: pyssword032.c:(.text+0x16bbe): undefined reference to `PyDict_SetItem'
    /usr/bin/ld: pyssword032.c:(.text+0x16c74): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x16c7f): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_PyObject_IsTrue':
    pyssword032.c:(.text+0x16cef): undefined reference to `_Py_TrueStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x16d08): undefined reference to `_Py_FalseStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x16d1e): undefined reference to `_Py_NoneStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x16d4a): undefined reference to `PyObject_IsTrue'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx__PyObject_CallOneArg':
    pyssword032.c:(.text+0x16d76): undefined reference to `PyTuple_New'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CLineForTraceback':
    pyssword032.c:(.text+0x16ea6): undefined reference to `_PyObject_GetDictPtr'
    /usr/bin/ld: pyssword032.c:(.text+0x16f1f): undefined reference to `_PyDict_GetItem_KnownHash'
    /usr/bin/ld: pyssword032.c:(.text+0x16f6c): undefined reference to `PyObject_Not'
    /usr/bin/ld: pyssword032.c:(.text+0x16f75): undefined reference to `_Py_TrueStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x16f7c): undefined reference to `_Py_FalseStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x16f9a): undefined reference to `PyErr_Clear'
    /usr/bin/ld: pyssword032.c:(.text+0x16fce): undefined reference to `_Py_FalseStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x16fd3): undefined reference to `PyObject_SetAttr'
    /usr/bin/ld: pyssword032.c:(.text+0x16fdf): undefined reference to `_Py_FalseStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x16ff0): undefined reference to `_Py_TrueStruct'
    /usr/bin/ld: pyssword032.c:(.text+0x17003): undefined reference to `PyObject_Not'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__Pyx_CreateCodeObjectForTraceback':
    pyssword032.c:(.text+0x171c8): undefined reference to `PyUnicode_FromFormat'
    /usr/bin/ld: pyssword032.c:(.text+0x171e5): undefined reference to `PyUnicode_AsUTF8'
    /usr/bin/ld: pyssword032.c:(.text+0x17213): undefined reference to `PyCode_NewEmpty'
    /usr/bin/ld: /tmp/pyssword032-799af8.o: in function `__pyx_insert_code_object':
    pyssword032.c:(.text+0x172b2): undefined reference to `PyMem_Malloc'
    /usr/bin/ld: pyssword032.c:(.text+0x173d8): undefined reference to `PyMem_Realloc'
    clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
